#!/bin/bash

echo "========================================="
echo "📋 FINAL STEP: Update Your API Key"
echo "========================================="
echo ""
echo "✅ COMPLETED:"
echo "  - API key removed from all files"
echo "  - Git history cleaned (old key is gone)"
echo "  - Changes pushed to GitHub"
echo "  - Backup branch created: backup-before-history-clean"
echo ""
echo "⚠️  ACTION REQUIRED:"
echo ""
echo "1. GET NEW API KEY from HouseCall Pro:"
echo "   → Log in to: https://pro.housecallpro.com/"
echo "   → Go to: Settings → Integrations → API"
echo "   → Click 'Regenerate API Key' or 'Revoke' the old key"
echo "   → Copy your NEW API key"
echo ""
echo "2. UPDATE housecallpro-config.js:"
echo "   → Open: housecallpro-config.js"
echo "   → Replace '9a480eda745743d28a7f3cf00ac5a58f' with your NEW key"
echo "   → Save the file"
echo ""
echo "3. TEST the integration:"
echo "   → Open any webpage with 'Schedule Now' button"
echo "   → Click it - HouseCall Pro popup should open"
echo ""
echo "Your housecallpro-config.js will NOT be committed to Git (it's gitignored)"
echo ""
echo "========================================="
echo "Need help? Check SECURITY-README.md"
echo "========================================="
